name: CI
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_EC2_METADATA_DISABLED: true
    steps:
      - name: Chekout
        uses: actions/checkout@v2
 
      - name: Copy files to primary bucket with the AWS CLI
        run: |
          aws s3 sync ./deploy s3://${{ secrets.S3_BUCKET }}
